name: "Submit to Web Store"
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*' # Trigger on version tags

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 22.x
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Build the extension
        run: pnpm build
      - name: Package the extension into a zip artifact
        run: pnpm build --target=chrome-mv3 --zip
      - name: Package the extension into a zip artifact for firefox
        run: pnpm build --target=firefox-mv3 --zip

      - name: Upload Chrome artifact
        uses: actions/upload-artifact@v4
        with:
          name: chrome-mv3-prod
          path: build/chrome-mv3-prod.zip

      - name: Upload Firefox artifact
        uses: actions/upload-artifact@v4
        with:
          name: firefox-mv3-prod
          path: build/firefox-mv3-prod.zip

  publish-chrome:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Chrome artifact
        uses: actions/download-artifact@v4
        with:
          name: chrome-mv3-prod
          path: build

      - name: Publish to Chrome Web Store
        uses: PlasmoHQ/bpp@v3
        with:
          keys: ${{ secrets.SUBMIT_KEYS }}
          chrome-file: "build/chrome-mv3-prod.zip"
          verbose: true

  publish-firefox:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Firefox artifact
        uses: actions/download-artifact@v4
        with:
          name: firefox-mv3-prod
          path: build

      - name: Publish to Firefox Add-ons
        uses: PlasmoHQ/bpp@v3
        with:
          keys: ${{ secrets.SUBMIT_KEYS }}
          firefox-file: "build/firefox-mv3-prod.zip"
          verbose: true
