name: "Submit to Web Store"
on:
  # todo: submit on tag instead of workflow_dispatch.
  workflow_dispatch:
  push:
    tags:
      - 'v*' # Trigger on version tags

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: latest
          run_install: true
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 22.x
          cache: "pnpm"
      - name: Build the extension
        run: pnpm build
      - name: Package the extension into a zip artifact
        run: pnpm build --target=chrome-mv3 --zip
      - name: Package the extension into a zip artifact for firefox
        run: pnpm build --target=firefox-mv2 --zip
      - name: Browser Platform Publish
        uses: PlasmoHQ/bpp@v3
        with:
          keys: ${{ secrets.SUBMIT_KEYS }}
          artifact: build/chrome-mv3-prod.zip
          chrome-file: "build/chrome-mv3-prod.zip"
          firefox-file: "build/firefox-mv2-prod.zip"
          version-file: "src/manifest.json"
          verbose: true
